### ISSUE TITLE
/check-url is returning 504 error code when timeout is set to a value > 29

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iari#726]
The check-url endpoint  for one of the Easter Island URLs is::

https://archive.org/services/context/wari/v2/check-url?url=https%3A%2F%2Fresultados.censo2017.cl%2FHome%2FDownload&refresh=true&timeout=30

The timeout is set to 30 seconds. It seems any value above 29 is giving a 504 status code back from archive.org for the WARI call, rather than a 200. This is causing the WARE url fetch loop to bomb (at the moment), as it doesn’t handle this error very well - it currently results in the UI reporting “No URLs to show!”

the WARI /check-url endpoint should return something to indicate the status of the url check is unknown up to the timeout value specified, rather than a 504
![gateway29](https://user-images.githubusercontent.com/550079/230620265-7cef542d-e03c-4bf2-9e76-b655186ac8ab.png)
![gateway30](https://user-images.githubusercontent.com/550079/230620273-5abd66c8-13d8-48cb-ba88-6f3ddabde5d6.png)
![gateway60](https://user-images.githubusercontent.com/550079/230620274-065c162f-0ec3-442b-bd93-7a0c6c2607d1.png)

**Comment by dpriskorn** [comment]
This is probably caused my nginx settings since gunicorn has a timeout of 200s.

**Comment by dpriskorn** [comment]
Cannot reproduce with other url:
![image](https://user-images.githubusercontent.com/68460690/230703857-83000895-178e-4bbd-b834-07e2250dec96.png)
http://18.217.22.248/v2/check-url?url=https://www.easterisland.travel&refresh=true&timeout=40
Cannot reproduce with http://18.217.22.248/v2/check-url?url=https%3A%2F%2Fresultados.censo2017.cl%2FHome%2FDownload&refresh=true&timeout=30
![image](https://user-images.githubusercontent.com/68460690/230703993-a6628dc2-e9fc-4828-9946-3e87db7da664.png)

The problem is in the proxy, I have notified the person responsible. A quick fix will be to use the non-proxy url until the settings of the nginx proxy have been fixed.

**Comment by dpriskorn** [comment]
This should now be fixed
