### ISSUE TITLE
as a patron I want usage instructions for setting up the API in the readme

### ISSUE THREAD

**Issue by harej** [internetarchive/iari#740]
I now have WARI set up on another server and I have no idea how to use it.

https://check-references.toolforge.org/v2/statistics/all

says URL is missing

https://check-references.toolforge.org/v2/statistics/all?url=https://en.wikipedia.org/wiki/Vaccine

says: "error": "{'regex': ['Missing data for required field.']}"

What required field? What am I missing?

**Comment by dpriskorn** [comment]
The in repository documentation is really not great.

I'm not currently linking to the WARI google document because I'm uncertain if it is public or not 🤷‍♂️

Swagger and redoc documentation is the way forward but for that we need a rewrite to fastapi.

regex is a new parameter introduced very recently. It is mandatory for now and the error message is not customized yet. You can set it to "test" to get going but then WARI will not find any general references in the wikitext.

**Comment by harej** [comment]
No need to overcomplicate this. All I want are simple instructions added to the README how to use the service I just set up.

**Comment by harej** [comment]
What does the `regex` parameter do? Why is it mandatory? Why would I set it to a value that makes the service useless? I would rather know what it does.
