### ISSUE TITLE
When a /check-url endpoint returns a 504 status, statusText in response is empty

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/iari#741]
It would be nice to have some sort of message in the statusText response field so the information describing the problem can be relayed to the patron

**Comment by dpriskorn** [comment]
https://http.cat/504 = gateway timeout

So you want nginx to tell you clearly that it timed out?

Isn't that clear from the status code alone?

If the python code beneath time-out because your set value of timeout is reached you get a 200 and timeout=true in the object.

Third case is gunicorn killing the worker after 200s. I'm a little unsure what that looks like to the client.

**Comment by dpriskorn** [comment]
abandoned, this is not a priority
